trigger:
  branches:
    exclude:
    - "*"
    - refs/tags/*
    - refs/heads/*

schedules:
- cron: "0 */6 * * *"
  displayName: Every 6 hours
  branches:
    include:
    - master
  always: true # run even if there's no source changes

resources:
- repo: self

variables:
  - group: AmphoraData
  - group: WeatherZone


stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: docker build -t $TAG $(Build.SourcesDirectory)/python-WeatherZone
      displayName: Build an image
      env:
        TAG: '$(Build.BuildId)'
      